<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 210%;text-align: center;border-radius: 10px 70px">
Python-SQL Workflow & Data Engineering Highlights
</center></p></h1>

<a class="anchor" id="setup"></a>
<br>
<br>
<br>
<font style="font-family:Gabriola; font-size:300%;">1️⃣ Step 1 | About Dataset </font><br>
 <br>   
<br>

<div style="border-radius: 5px;
           -webkit-border-radius: 5px;
           -moz-border-radius: 5px;
           font-family: cursive;
           border: 3px solid #008000;
           text-align: justify;
           color: black;
           font-size: 14px;
           padding: 5px;
           background:#F2FFFF">

  <p style="text-align: justify; font-family: cursive; font-size: 14px; color : green ; font-weight : bold">
    About Dataset
  </p>

  <p style="text-align: justify; font-family: cursive; font-size: 14px; color : black">
    This study improves predictive accuracy in electrochemical methane (CH₄) conversion by applying advanced preprocessing,
    feature engineering (polynomial + interaction features), and robust validation using <b>k-fold cross-validation</b>.
    The dataset contains <b>123 rows</b> and <b>39 variables</b>, covering catalyst composition, operating conditions,
    and electrochemical performance metrics. Experiments include <b>Electrolyzer</b> as the main process type, while also
    incorporating <b>Electrochemical devices</b> and <b>Solar light</b> systems. The modeling focuses on predicting
    <b>methanol yield</b> and <b>ethanol yield</b>, and analyzing the influence of process parameters such as
    <b>light intensity (0–175 mW/cm²)</b>, voltage, and current density on catalyst activity.
  </p>

  <p style="text-align: justify; font-family: cursive; font-size: 14px; color : black">
    <b>Data Source Structure:</b> The original Excel file contains <b>4 separate sheets</b> representing different experimental subsets
    (e.g., electrolyzer, electrochemical devices, solar-assisted conditions, and additional catalyst/process records). All sheets were
    extracted individually, standardized to a unified schema, and then <b>concatenated into one final master dataset</b> for EDA and machine learning.
  </p>

  <p><b>Dataset Snapshot (First 5 Rows)</b></p>
  <div style="overflow-x:auto;">
    <table border="1" class="dataframe">
      <thead>
        <tr style="text-align: right;">
          <th></th>
          <th>Cathod Catalyst</th>
          <th>Anode Catalyst</th>
          <th>Pt at% in metal element</th>
          <th>Co at% in metal element</th>
          <th>Ni at% in metal element</th>
          <th>Pd at% in metal element</th>
          <th>Ir at% in metal element</th>
          <th>Zr at% in metal element</th>
          <th>Ru at% in metal element</th>
          <th>Grahene % as support</th>
          <th>...</th>
          <th>Current at 1.5 V</th>
          <th>Current at 1.6 V</th>
          <th>Current at 1.7 V</th>
          <th>Current at 1.8 V</th>
          <th>Current at 1.9 V</th>
          <th>Current at 2.0 V</th>
          <th>Operating Pressure (bar)</th>
          <th>Current Density mA/cm²</th>
          <th>Reaction Time (hr)</th>
          <th>Process type</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>0</th>
          <td>Ni-Tio2</td>
          <td>IrO₂</td>
          <td>-1</td>
          <td>1</td>
          <td>89</td>
          <td>0</td>
          <td>0</td>
          <td>0.388158</td>
          <td>0.465456</td>
          <td>0.287554</td>
          <td>...</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>1.004461</td>
          <td>31.555958</td>
          <td>2</td>
          <td>Electrolyzer</td>
        </tr>
        <tr>
          <th>1</th>
          <td>Pd-Ni/CeO2</td>
          <td>IrO₂</td>
          <td>1</td>
          <td>1</td>
          <td>1</td>
          <td>0</td>
          <td>0</td>
          <td>-0.110492</td>
          <td>0.213468</td>
          <td>-0.126233</td>
          <td>...</td>
          <td>0.121830</td>
          <td>0.420827</td>
          <td>0.847900</td>
          <td>1.238966</td>
          <td>1.618621</td>
          <td>2.018211</td>
          <td>1.005696</td>
          <td>86.842445</td>
          <td>6</td>
          <td>Electrolyzer</td>
        </tr>
        <tr>
          <th>2</th>
          <td>Pt-Co/TiO2/g-C3N4</td>
          <td>NiFeO2</td>
          <td>48</td>
          <td>51</td>
          <td>0</td>
          <td>0</td>
          <td>1</td>
          <td>0.335529</td>
          <td>-0.455251</td>
          <td>-0.057967</td>
          <td>...</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>NaN</td>
          <td>0.999690</td>
          <td>80.215411</td>
          <td>9</td>
          <td>Solar light</td>
        </tr>
        <tr>
          <th>3</th>
          <td>Ru/TiO2/g-C3N4</td>
          <td>IrO₂</td>
          <td>-1</td>
          <td>0</td>
          <td>1</td>
          <td>0</td>
          <td>0</td>
          <td>-0.441902</td>
          <td>99.305976</td>
          <td>-0.791599</td>
          <td>...</td>
          <td>0.253608</td>
          <td>0.793055</td>
          <td>1.374248</td>
          <td>2.051113</td>
          <td>2.637428</td>
          <td>3.175515</td>
          <td>0.994959</td>
          <td>63.177526</td>
          <td>6</td>
          <td>Electrochemical devices</td>
        </tr>
        <tr>
          <th>4</th>
          <td>Pt/TiO2</td>
          <td>IrO₂</td>
          <td>100</td>
          <td>1</td>
          <td>1</td>
          <td>0</td>
          <td>-1</td>
          <td>-0.205660</td>
          <td>0.044834</td>
          <td>-0.114413</td>
          <td>...</td>
          <td>0.222016</td>
          <td>0.537653</td>
          <td>0.859000</td>
          <td>1.113203</td>
          <td>1.474970</td>
          <td>2.021662</td>
          <td>1.561931</td>
          <td>54.845526</td>
          <td>6</td>
          <td>Electrolyzer</td>
        </tr>
      </tbody>
    </table>
    <p style="margin: 5px 0px;"><i>Preview: 5 rows × 39 columns</i></p>
  </div>

  <p><b>Key Dataset Components</b></p>
  <ul>
    <li><b>Catalysts:</b> Includes Pt, Co, Ni, Ru, Pd, Ir-based and hybrid catalyst compositions (e.g., Pt/C, Ni–TiO₂, Pt–Co/TiO₂/g-C₃N₄).</li>
    <li><b>Supports:</b> Materials improving catalyst performance and dispersion (e.g., TiO₂, g-C₃N₄, carbon-based supports such as graphene).</li>
    <li><b>Experimental Conditions:</b> Voltage, current density, electrolyte type/concentration, CH₄ flow rate, operating pressure, reaction time, and light intensity.</li>
    <li><b>Process Types:</b> Mainly <b>Electrolyzer</b>, with additional records from <b>Electrochemical devices</b> and <b>Solar light</b> assisted experiments.</li>
    <li><b>Outputs:</b> Methanol and ethanol yields, and electrochemical performance (current response at multiple voltage points).</li>
  </ul>

</div>

<a class="anchor" id="data"></a>
<br>
<br>
<br>
<font style="font-family:Gabriola; font-size:300%;">2️⃣  Step 3 | Objective
 </font><br>
 <br>   
<br>

<div style="border-radius:5px; border:3px solid #008000; background:#F2FFFF; padding:10px; font-family:cursive; font-size:14px; color:black; text-align:justify;">

  <p style="font-weight:bold; color:green; font-size:15px;">Project Achievements: Database Integration & Python-SQL Workflow</p>
  <ul>
    <li>Established robust connection to relational database using <b>SQLAlchemy</b> for automated data extraction and storage.</li>
    <li>Implemented <b>ETL pipeline</b> with Python to read multi-sheet experimental datasets via <b>pandas pd.read_sql()</b>, perform preprocessing, and load cleaned data back to SQL tables.</li>
    <li>Designed SQL queries for flexible aggregation, filtering, and feature extraction directly from Python, enabling scalable data analysis and ML-ready datasets.</li>
    <li>Automated dataset refresh and preprocessing workflows to ensure reproducibility and seamless integration with <b>ensemble ML models</b>.</li>
    <li>Handled large-scale experimental data across multiple device types while maintaining data integrity, type consistency, and standardized categorical labels.</li>
  </ul>

</div>

<a class="anchor" id="setup"></a>
<br>
<br>
<br>
<font style="font-family:Gabriola; font-size:300%;">3️⃣ Step 2 | Python Libraries </font><br>
 <br>   
<br>

In [8]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.pipeline import Pipeline,make_pipeline
import sqlalchemy 
from sqlalchemy import create_engine
import _mysql_connector

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer


import warnings 
warnings.filterwarnings('ignore')

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      Data Loading  
</center></p></h1>

In [ ]:
df_1 = pd.read_excel('Dataset.xlsx', sheet_name=1)
df_1.head()

,Cathod Catalyst,Anode Catalyst,Pt at% in metal element,Co at% in metal element,Ni at% in metal element,Pd at% in metal element,Ir at% in metal element,Zr at% in metal element,Ru at% in metal element,Grahene % as support,...,Current at 1.5 V,Current at 1.6 V,Current at 1.7 V,Current at 1.8 V,Current at 1.9 V,Current at 2.0 V,Operating Pressure (bar),Current Density mA/cm²,Reaction Time (hr),Process type
0,Ni-Tio2,IrO₂,-1,1,89,0,0,0.388158,0.465456,0.287554,...,NaN,NaN,NaN,NaN,NaN,NaN,1.004461,31.555958,2,Electrolyzer
1,Pd-Ni/CeO2,IrO₂,1,1,1,0,0,-0.110492,0.213468,-0.126233,...,0.121830,0.420827,0.847900,1.238966,1.618621,2.018211,1.005696,86.842445,6,Electrolyzer
2,Pt-Co/TiO2/g-C3N4,NiFeO2,48,51,0,0,1,0.335529,-0.455251,-0.057967,...,NaN,NaN,NaN,NaN,NaN,NaN,0.999690,80.215411,9,Solar light
3,Ru/TiO2/g-C3N4,IrO₂,-1,0,1,0,0,-0.441902,99.305976,-0.791599,...,0.253608,0.793055,1.374248,2.051113,2.637428,3.175515,0.994959,63.177526,6,Electrochemical devices
4,Pt/TiO2,IrO₂,100,1,1,0,-1,-0.205660,0.044834,-0.114413,...,0.222016,0.537653,0.859000,1.113203,1.474970,2.021662,1.561931,54.845526,6,Electrolyzer

In [ ]:
df_2 = pd.read_excel('Dataset.xlsx', sheet_name=2)
df_2.head()

,Cathod Catalyst,Anode Catalyst,Pt at% in metal element,Co at% in metal element,Ni at% in metal element,Pd at% in metal element,Ir at% in metal element,Zr at% in metal element,Ru at% in metal element,Grahene % as support,...,Current at 1.5 V,Current at 1.6 V,Current at 1.7 V,Current at 1.8 V,Current at 1.9 V,Current at 2.0 V,Operating Pressure (bar),Current Density mA/cm²,Reaction Time (hr),Process type
0,40wt%_Pt/C,IrO₂,40,0,-1,0,0,0.160534,0.908211,0.787179,...,0.118334,0.625295,1.636374,2.950411,4.373769,5.716843,1.007789,27.949153,6,Electrolyzer
1,Pt-Co/TiO2/g-C3N4,RuO₂,31,68,0,0,1,0.302529,-0.496339,0.658210,...,0.099496,0.784034,2.304795,4.460217,6.497564,8.527097,0.998574,80.139053,2,Electrolyzer
2,Carbon Paper,IrO₂,1,0,-1,0,0,0.813352,0.638004,0.376839,...,0.027106,0.276462,0.970256,1.767202,2.562104,3.452943,1.000523,19.399854,6,Electrolyzer
3,Pt-Co/TiO2/g-C3N4,IrO₂,51,50,0,0,0,-0.204443,-0.300742,0.219100,...,NaN,NaN,NaN,NaN,NaN,NaN,0.994810,78.944311,6,Solar light
4,Tio2/g-C3N4,IrO₂,0,1,-2,0,0,-0.340441,-0.113095,-0.066808,...,0.016911,0.082624,0.089199,0.152337,0.218502,0.315138,1.562204,26.569737,6,Solar light

In [ ]:
df_3 = pd.read_excel('Dataset.xlsx', sheet_name=3)
df_3.head()

,Cathod Catalyst,Anode Catalyst,Pt at% in metal element,Co at% in metal element,Ni at% in metal element,Pd at% in metal element,Ir at% in metal element,Zr at% in metal element,Ru at% in metal element,Grahene % as support,...,Current at 1.5 V,Current at 1.6 V,Current at 1.7 V,Current at 1.8 V,Current at 1.9 V,Current at 2.0 V,Operating Pressure (bar),Current Density mA/cm²,Reaction Time (hr),Process type
0,Co/TiO2,IrO₂,1,99,0,0,0,-0.442968,-0.125263,0.288814,...,0.028373,0.141994,0.201190,0.266126,0.406836,0.487384,1.567363,44.036081,6,Electrolyzer
1,Pt-Co/TiO2/g-C3N4,IrO₂,50,49,0,0,0,0.149064,0.302541,0.018813,...,0.003468,0.140874,0.342725,0.602499,0.887557,1.095561,1.006242,79.234958,6,Solar light
2,Pt-Co/TiO2/g-C3N4,IrO₂,51,50,0,0,1,0.442625,-0.052292,0.071320,...,0.011414,0.162392,0.341543,0.596032,0.787599,1.075289,1.005399,80.604052,6,Electrolyzer
3,Pd-Ni/CeO2,IrO₂,-1,1,0,0,1,-0.458573,0.726556,0.168978,...,0.014200,0.109187,0.225699,0.472511,0.713196,1.077611,1.003412,85.243720,6,Electrolyzer
4,Pt/TiO2,IrO₂,101,1,1,0,0,-0.209942,0.370960,0.376460,...,0.742769,0.864122,0.972162,0.967827,0.946734,1.031984,0.994477,51.299970,8,Electrolyzer

In [ ]:
df_4 = pd.read_excel('Dataset.xlsx', sheet_name=4)
df_4.head()

,Cathod Catalyst,Anode Catalyst,Pt at% in metal element,Co at% in metal element,Ni at% in metal element,Pd at% in metal element,Ir at% in metal element,Zr at% in metal element,Ru at% in metal element,Grahene % as support,...,Current at 2.0 V,Operating Pressure (bar),Current Density mA/cm²,Reaction Time (hr),Process type,anomaly_flag,degradation_rate_est,maintenance_reason,maintenance_needed,failure_risk_level
0,Carbon Paper,NaN,0,0,0,0,0,0.0,0.0,0.0,...,NaN,NaN,20.0,2,Electrochemical devices,0,-0.001032,normal,0.0,normal
1,Carbon Paper,NaN,0,0,0,0,0,0.0,0.0,0.0,...,NaN,NaN,20.0,6,Solar light,0,0.000945,normal,0.0,normal
2,Carbon Paper,IrO₂,0,0,0,0,0,0.0,0.0,0.0,...,6.52660,1.0,16.0,6,Electrolyzer,0,0.001173,normal,0.0,normal
3,Carbon Paper,IrO₂,0,0,0,0,0,0.0,0.0,0.0,...,3.25241,1.0,14.0,4,Electrolyzer,0,0.000683,normal,0.0,normal
4,Carbon Paper,IrO₂,0,0,0,0,0,0.0,0.0,0.0,...,3.45586,1.0,21.0,6,Electrolyzer,0,-0.001688,normal,0.0,normal

In [13]:
df_0= df_4.iloc[:, :-5]
df_0.head()

,Cathod Catalyst,Anode Catalyst,Pt at% in metal element,Co at% in metal element,Ni at% in metal element,Pd at% in metal element,Ir at% in metal element,Zr at% in metal element,Ru at% in metal element,Grahene % as support,...,Current at 1.5 V,Current at 1.6 V,Current at 1.7 V,Current at 1.8 V,Current at 1.9 V,Current at 2.0 V,Operating Pressure (bar),Current Density mA/cm²,Reaction Time (hr),Process type
0,Carbon Paper,NaN,0,0,0,0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,2,Electrochemical devices
1,Carbon Paper,NaN,0,0,0,0,0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,6,Solar light
2,Carbon Paper,IrO₂,0,0,0,0,0,0.0,0.0,0.0,...,0.27126,0.86561,2.00570,3.49714,5.01187,6.52660,1.0,16.0,6,Electrolyzer
3,Carbon Paper,IrO₂,0,0,0,0,0,0.0,0.0,0.0,...,0.18773,0.52738,1.01149,1.54244,2.32813,3.25241,1.0,14.0,4,Electrolyzer
4,Carbon Paper,IrO₂,0,0,0,0,0,0.0,0.0,0.0,...,0.03120,0.28642,0.94636,1.78286,2.61936,3.45586,1.0,21.0,6,Electrolyzer

In [14]:
df= pd.concat([df_1, df_2, df_3],axis=0)

In [15]:
df.head()

,Cathod Catalyst,Anode Catalyst,Pt at% in metal element,Co at% in metal element,Ni at% in metal element,Pd at% in metal element,Ir at% in metal element,Zr at% in metal element,Ru at% in metal element,Grahene % as support,...,Current at 1.5 V,Current at 1.6 V,Current at 1.7 V,Current at 1.8 V,Current at 1.9 V,Current at 2.0 V,Operating Pressure (bar),Current Density mA/cm²,Reaction Time (hr),Process type
0,Ni-Tio2,IrO₂,-1,1,89,0,0,0.388158,0.465456,0.287554,...,NaN,NaN,NaN,NaN,NaN,NaN,1.004461,31.555958,2,Electrolyzer
1,Pd-Ni/CeO2,IrO₂,1,1,1,0,0,-0.110492,0.213468,-0.126233,...,0.121830,0.420827,0.847900,1.238966,1.618621,2.018211,1.005696,86.842445,6,Electrolyzer
2,Pt-Co/TiO2/g-C3N4,NiFeO2,48,51,0,0,1,0.335529,-0.455251,-0.057967,...,NaN,NaN,NaN,NaN,NaN,NaN,0.999690,80.215411,9,Solar light
3,Ru/TiO2/g-C3N4,IrO₂,-1,0,1,0,0,-0.441902,99.305976,-0.791599,...,0.253608,0.793055,1.374248,2.051113,2.637428,3.175515,0.994959,63.177526,6,Electrochemical devices
4,Pt/TiO2,IrO₂,100,1,1,0,-1,-0.205660,0.044834,-0.114413,...,0.222016,0.537653,0.859000,1.113203,1.474970,2.021662,1.561931,54.845526,6,Electrolyzer

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      DATABASE Connection 
</center></p></h1>

In [22]:


# Connect to Database
user = "amir"
password = "Reza1071"
host = "localhost"
port = 3306
database = "Electrolyzer_db"
#  read Data
table_name = "preprocessed"



# Create connection
engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

In [ ]:
# Clean column names
df.columns = (
    df.columns
    .str.strip()                      # remove leading/trailing spaces
    .str.replace(" ", "_")            # spaces → underscore
    .str.replace("%", "percent")      # % → percent
    .str.replace("µ", "micro")        # µ → micro
    .str.replace("²", "2")            # ² → 2
    .str.replace("/", "_", regex=False)
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace("-", "_"))

print(df.columns)

Index(['Cathod_Catalyst', 'Anode_Catalyst', 'Pt_atpercent_in_metal_element',
       'Co_atpercent_in_metal_element', 'Ni_atpercent_in_metal_element',
       'Pd_atpercent_in_metal_element', 'Ir_atpercent_in_metal_element',
       'Zr_atpercent_in_metal_element', 'Ru_atpercent_in_metal_element',
       'Grahene_percent__as_support', 'Biocatalystpercent',
       'TiO2_percent_as_support', 'CeO2_percent_as_support',
       'g_C3N4_percent__as_support', 'Cpercent_as_support',
       'Total_Metal_Loading_percent', 'BET_surface_aream2_g', 'Ink__I_C_Ratio',
       'Membrance_Type', 'Active_Area_cm2', 'Ionomer_Type',
       'Anode_Metal_Loading_mg_cm2__Ir_Ru_Pt_Pd', 'Cathode_Loading_mg_cm2',
       'Electrolyte', 'Ligh_Intensity_mW_cm2_', 'CH4_Flow_rate_sscm',
       'Methanol_Yield_micromol_ml_', 'Ethanol_Yield_micromol_ml_',
       'Voltage_V', 'Current_at_1.5_V', 'Current_at_1.6_V', 'Current_at_1.7_V',
       'Current_at_1.8_V', 'Current_at_1.9_V', 'Current_at_2.0_V',
       'Operating_Pressure_bar', 'Current_Density_mA_cm2', 'Reaction_Time_hr',
       'Process_type'],
      dtype='object')

In [ ]:
# ---- Send data to MySQL ----
df.to_sql(
    table_name,
    con=engine,
    if_exists='replace',  # 'append' 
    index=False)

print("Data successfully loaded back into the database!")

Data successfully loaded back into the database!

In [ ]:

df = pd.read_sql(f"SELECT * FROM {table_name}", con=engine)
print(f"Initial data shape: {df.shape}")

Initial data shape: (498, 39)

In [29]:
df.head()

,Cathod_Catalyst,Anode_Catalyst,Pt_atpercent_in_metal_element,Co_atpercent_in_metal_element,Ni_atpercent_in_metal_element,Pd_atpercent_in_metal_element,Ir_atpercent_in_metal_element,Zr_atpercent_in_metal_element,Ru_atpercent_in_metal_element,Grahene_percent__as_support,...,Current_at_1.5_V,Current_at_1.6_V,Current_at_1.7_V,Current_at_1.8_V,Current_at_1.9_V,Current_at_2.0_V,Operating_Pressure_bar,Current_Density_mA_cm2,Reaction_Time_hr,Process_type
0,Ni-Tio2,IrO₂,-1,1,89,0,0,0.388158,0.465456,0.287554,...,NaN,NaN,NaN,NaN,NaN,NaN,1.004461,31.555958,2,Electrolyzer
1,Pd-Ni/CeO2,IrO₂,1,1,1,0,0,-0.110492,0.213468,-0.126233,...,0.121830,0.420827,0.847900,1.238966,1.618621,2.018211,1.005696,86.842445,6,Electrolyzer
2,Pt-Co/TiO2/g-C3N4,NiFeO2,48,51,0,0,1,0.335529,-0.455251,-0.057967,...,NaN,NaN,NaN,NaN,NaN,NaN,0.999690,80.215411,9,Solar light
3,Ru/TiO2/g-C3N4,IrO₂,-1,0,1,0,0,-0.441902,99.305976,-0.791599,...,0.253608,0.793055,1.374248,2.051113,2.637428,3.175515,0.994959,63.177526,6,Electrochemical devices
4,Pt/TiO2,IrO₂,100,1,1,0,-1,-0.205660,0.044834,-0.114413,...,0.222016,0.537653,0.859000,1.113203,1.474970,2.021662,1.561931,54.845526,6,Electrolyzer

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
      Basic Understanding Data  
</center></p></h1>

In [30]:


def check_df(df, name="Dataset", head=5):
    print("\n" + "="*60)
    print(f" DATASET OVERVIEW: {name}")
    print("="*60)

    # 1. Shape
    print("\n SHAPE")
    print(f"Rows: {df.shape[0]} | Columns: {df.shape[1]}")

    # 2. Data Types (per column)
    print("\n DATA TYPES (PER COLUMN)")
    print(df.dtypes)

    # 3. Data Type Summary
    print("\n DATA TYPE SUMMARY")
    print(df.dtypes.value_counts())

    # 4. Info
    print("\n INFO")
    df.info()

    # 5. Head
    print("\n HEAD")
    display(df.head(head))

    # 6. Tail
    print("\n TAIL")
    display(df.tail(head))

    # 7. Missing Values
    print("\n MISSING VALUES")
    print(df.isnull().sum())

    # 8. Duplicate Rows
    print("\n DUPLICATE ROWS")
    print(f"Number of duplicate rows: {df.duplicated().sum()}")

    # 9. Descriptive Statistics (numeric only)
    print("\n DESCRIPTIVE STATISTICS (NUMERIC)")
    display(df.describe())

In [31]:
check_df(df, "Electolyzer - CH4 Conversion")

============================================================
 DATASET OVERVIEW: Electolyzer - CH4 Conversion
============================================================

 SHAPE
Rows: 498 | Columns: 39

 DATA TYPES (PER COLUMN)
Cathod_Catalyst                             object
Anode_Catalyst                              object
Pt_atpercent_in_metal_element                int64
Co_atpercent_in_metal_element                int64
Ni_atpercent_in_metal_element                int64
Pd_atpercent_in_metal_element                int64
Ir_atpercent_in_metal_element                int64
Zr_atpercent_in_metal_element              float64
Ru_atpercent_in_metal_element              float64
Grahene_percent__as_support                float64
Biocatalystpercent                         float64
TiO2_percent_as_support                      int64
CeO2_percent_as_support                    float64
g_C3N4_percent__as_support                   int64
Cpercent_as_support                          int64
Total_Metal_Loading_percent                float64
BET_surface_aream2_g                       float64
Ink__I_C_Ratio                              object
Membrance_Type                              object
Active_Area_cm2                              int64
Ionomer_Type                                object
Anode_Metal_Loading_mg_cm2__Ir_Ru_Pt_Pd    float64
Cathode_Loading_mg_cm2                     float64
Electrolyte                                 object
Ligh_Intensity_mW_cm2_                       int64
CH4_Flow_rate_sscm                           int64
Methanol_Yield_micromol_ml_                float64
Ethanol_Yield_micromol_ml_                 float64
Voltage_V                                  float64
Current_at_1.5_V                           float64
Current_at_1.6_V                           float64
Current_at_1.7_V                           float64
Current_at_1.8_V                           float64
Current_at_1.9_V                           float64
Current_at_2.0_V                           float64
Operating_Pressure_bar                     float64
Current_Density_mA_cm2                     float64
Reaction_Time_hr                             int64
Process_type                                object
dtype: object

 DATA TYPE SUMMARY
float64    20
int64      12
object      7
Name: count, dtype: int64

 INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 39 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Cathod_Catalyst                          498 non-null    object
 1   Anode_Catalyst                           498 non-null    object
 2   Pt_atpercent_in_metal_element            498 non-null    int64
 3   Co_atpercent_in_metal_element            498 non-null    int64
 4   Ni_atpercent_in_metal_element            498 non-null    int64
 5   Pd_atpercent_in_metal_element            498 non-null    int64
 6   Ir_atpercent_in_metal_element            498 non-null    int64
 7   Zr_atpercent_in_metal_element            495 non-null    float64
 8   Ru_atpercent_in_metal_element            495 non-null    float64
 9   Grahene_percent__as_support              495 non-null    float64
 10  Biocatalystpercent                       495 non-null    float64
 11  TiO2_percent_as_support                  498 non-null    int64
 12  CeO2_percent_as_support                  453 non-null    float64
 13  g_C3N4_percent__as_support               498 non-null    int64
 14  Cpercent_as_support                      498 non-null    int64
 15  Total_Metal_Loading_percent              497 non-null    float64
 16  BET_surface_aream2_g                     411 non-null    float64
 17  Ink__I_C_Ratio                           498 non-null    object
 18  Membrance_Type                           498 non-null    object
 19  Active_Area_cm2                          498 non-null    int64
 20  Ionomer_Type                             498 non-null    object
 21  Anode_Metal_Loading_mg_cm2__Ir_Ru_Pt_Pd  498 non-null    float64
 22  Cathode_Loading_mg_cm2                   498 non-null    float64
 23  Electrolyte                              498 non-null    object
 24  Ligh_Intensity_mW_cm2_                   498 non-null    int64
 25  CH4_Flow_rate_sscm                       498 non-null    int64
 26  Methanol_Yield_micromol_ml_              498 non-null    float64
 27  Ethanol_Yield_micromol_ml_               498 non-null    float64
 28  Voltage_V                                498 non-null    float64
 29  Current_at_1.5_V                         319 non-null    float64
 30  Current_at_1.6_V                         319 non-null    float64
 31  Current_at_1.7_V                         319 non-null    float64
 32  Current_at_1.8_V                         319 non-null    float64
 33  Current_at_1.9_V                         319 non-null    float64
 34  Current_at_2.0_V                         319 non-null    float64
 35  Operating_Pressure_bar                   495 non-null    float64
 36  Current_Density_mA_cm2                   498 non-null    float64
 37  Reaction_Time_hr                         498 non-null    int64
 38  Process_type                             498 non-null    object
dtypes: float64(20), int64(12), object(7)
memory usage: 151.9+ KB

 HEAD

,Cathod_Catalyst,Anode_Catalyst,Pt_atpercent_in_metal_element,Co_atpercent_in_metal_element,Ni_atpercent_in_metal_element,Pd_atpercent_in_metal_element,Ir_atpercent_in_metal_element,Zr_atpercent_in_metal_element,Ru_atpercent_in_metal_element,Grahene_percent__as_support,...,Current_at_1.5_V,Current_at_1.6_V,Current_at_1.7_V,Current_at_1.8_V,Current_at_1.9_V,Current_at_2.0_V,Operating_Pressure_bar,Current_Density_mA_cm2,Reaction_Time_hr,Process_type
0,Ni-Tio2,IrO₂,-1,1,89,0,0,0.388158,0.465456,0.287554,...,NaN,NaN,NaN,NaN,NaN,NaN,1.004461,31.555958,2,Electrolyzer
1,Pd-Ni/CeO2,IrO₂,1,1,1,0,0,-0.110492,0.213468,-0.126233,...,0.121830,0.420827,0.847900,1.238966,1.618621,2.018211,1.005696,86.842445,6,Electrolyzer
2,Pt-Co/TiO2/g-C3N4,NiFeO2,48,51,0,0,1,0.335529,-0.455251,-0.057967,...,NaN,NaN,NaN,NaN,NaN,NaN,0.999690,80.215411,9,Solar light
3,Ru/TiO2/g-C3N4,IrO₂,-1,0,1,0,0,-0.441902,99.305976,-0.791599,...,0.253608,0.793055,1.374248,2.051113,2.637428,3.175515,0.994959,63.177526,6,Electrochemical devices
4,Pt/TiO2,IrO₂,100,1,1,0,-1,-0.205660,0.044834,-0.114413,...,0.222016,0.537653,0.859000,1.113203,1.474970,2.021662,1.561931,54.845526,6,Electrolyzer

 TAIL

,Cathod_Catalyst,Anode_Catalyst,Pt_atpercent_in_metal_element,Co_atpercent_in_metal_element,Ni_atpercent_in_metal_element,Pd_atpercent_in_metal_element,Ir_atpercent_in_metal_element,Zr_atpercent_in_metal_element,Ru_atpercent_in_metal_element,Grahene_percent__as_support,...,Current_at_1.5_V,Current_at_1.6_V,Current_at_1.7_V,Current_at_1.8_V,Current_at_1.9_V,Current_at_2.0_V,Operating_Pressure_bar,Current_Density_mA_cm2,Reaction_Time_hr,Process_type
493,Pt/Graphite,IrO₂,100,0,-1,0,1,-0.087718,0.973292,74.322563,...,0.258978,0.659994,1.074592,1.481264,1.887779,2.263547,1.001247,42.130186,8,Electrolyzer
494,Pt-Co-Ni/TiO2/g-C3N4,IrO₂,49,24,26,0,0,-0.093455,0.257345,-0.254364,...,NaN,NaN,NaN,NaN,NaN,NaN,1.005446,50.237718,6,Solar light
495,Pt-Co/TiO2/g-C3N4,IrO₂,51,51,0,0,0,-0.049405,1.053011,1.029561,...,0.003916,0.110330,0.321006,0.533685,0.728730,1.033139,1.002958,79.983499,6,Electrolyzer
496,Pt-Co-Ni/TiO2/g-C3N4,IrO₂,71,20,10,0,0,-0.002316,0.484782,-0.254201,...,NaN,NaN,NaN,NaN,NaN,NaN,1.009260,55.878792,6,Solar light
497,Pt-Co/TiO2/g-C3N4 +Biocatalyst 2.5%,IrO₂,50,50,1,0,0,0.010101,-0.752656,0.754050,...,NaN,NaN,NaN,NaN,NaN,NaN,0.999683,66.761904,6,Solar light

 MISSING VALUES
Cathod_Catalyst                              0
Anode_Catalyst                               0
Pt_atpercent_in_metal_element                0
Co_atpercent_in_metal_element                0
Ni_atpercent_in_metal_element                0
Pd_atpercent_in_metal_element                0
Ir_atpercent_in_metal_element                0
Zr_atpercent_in_metal_element                3
Ru_atpercent_in_metal_element                3
Grahene_percent__as_support                  3
Biocatalystpercent                           3
TiO2_percent_as_support                      0
CeO2_percent_as_support                     45
g_C3N4_percent__as_support                   0
Cpercent_as_support                          0
Total_Metal_Loading_percent                  1
BET_surface_aream2_g                        87
Ink__I_C_Ratio                               0
Membrance_Type                               0
Active_Area_cm2                              0
Ionomer_Type                                 0
Anode_Metal_Loading_mg_cm2__Ir_Ru_Pt_Pd      0
Cathode_Loading_mg_cm2                       0
Electrolyte                                  0
Ligh_Intensity_mW_cm2_                       0
CH4_Flow_rate_sscm                           0
Methanol_Yield_micromol_ml_                  0
Ethanol_Yield_micromol_ml_                   0
Voltage_V                                    0
Current_at_1.5_V                           179
Current_at_1.6_V                           179
Current_at_1.7_V                           179
Current_at_1.8_V                           179
Current_at_1.9_V                           179
Current_at_2.0_V                           179
Operating_Pressure_bar                       3
Current_Density_mA_cm2                       0
Reaction_Time_hr                             0
Process_type                                 0
dtype: int64

 DUPLICATE ROWS
Number of duplicate rows: 0

 DESCRIPTIVE STATISTICS (NUMERIC)

,Pt_atpercent_in_metal_element,Co_atpercent_in_metal_element,Ni_atpercent_in_metal_element,Pd_atpercent_in_metal_element,Ir_atpercent_in_metal_element,Zr_atpercent_in_metal_element,Ru_atpercent_in_metal_element,Grahene_percent__as_support,Biocatalystpercent,TiO2_percent_as_support,...,Voltage_V,Current_at_1.5_V,Current_at_1.6_V,Current_at_1.7_V,Current_at_1.8_V,Current_at_1.9_V,Current_at_2.0_V,Operating_Pressure_bar,Current_Density_mA_cm2,Reaction_Time_hr
count,498.000000,498.000000,498.000000,498.000000,498.000000,495.000000,495.000000,495.000000,495.000000,498.000000,...,498.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,495.000000,498.000000,498.000000
mean,43.156627,17.273092,9.114458,1.493976,2.232932,1.010098,2.307551,3.788541,0.149517,50.550201,...,1.386348,0.154747,0.541579,1.075110,1.678319,2.297307,2.913747,1.041665,63.208143,5.405622
std,34.956420,24.539414,21.726787,7.519055,14.728186,10.000561,12.708406,17.109288,0.464616,41.722067,...,0.432948,0.167534,0.415969,0.791158,1.279350,1.809422,2.352937,0.155659,26.881001,1.672396
min,-2.000000,-2.000000,-2.000000,-1.000000,-1.000000,-0.978286,-1.411910,-1.598383,-0.036623,-4.000000,...,-0.015389,-0.010646,0.000045,-0.017566,-0.048093,0.009697,-0.100088,0.499852,-1.818639,2.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,-0.204777,-0.269748,-0.290875,-0.009457,1.000000,...,1.003700,0.037295,0.217010,0.497629,0.802438,1.034318,1.264108,0.997604,42.711443,4.000000
50%,50.000000,1.000000,0.000000,0.000000,0.000000,0.010998,0.040494,0.093670,0.000387,79.000000,...,1.491302,0.109864,0.461101,0.869451,1.325137,1.665807,2.111640,1.000191,76.229557,6.000000
75%,69.000000,49.000000,1.000000,0.000000,0.000000,0.203895,0.358568,0.488803,0.011438,88.000000,...,1.510317,0.183564,0.706491,1.612476,2.611768,3.552121,4.413201,1.003754,82.325432,6.000000
max,102.000000,101.000000,91.000000,50.000000,101.000000,100.401184,100.558535,100.438874,2.019023,102.000000,...,2.520432,0.750259,2.027794,3.858309,5.726266,7.541659,9.359521,1.582256,99.018141,12.000000

In [32]:
df.columns

Index(['Cathod_Catalyst', 'Anode_Catalyst', 'Pt_atpercent_in_metal_element',
       'Co_atpercent_in_metal_element', 'Ni_atpercent_in_metal_element',
       'Pd_atpercent_in_metal_element', 'Ir_atpercent_in_metal_element',
       'Zr_atpercent_in_metal_element', 'Ru_atpercent_in_metal_element',
       'Grahene_percent__as_support', 'Biocatalystpercent',
       'TiO2_percent_as_support', 'CeO2_percent_as_support',
       'g_C3N4_percent__as_support', 'Cpercent_as_support',
       'Total_Metal_Loading_percent', 'BET_surface_aream2_g', 'Ink__I_C_Ratio',
       'Membrance_Type', 'Active_Area_cm2', 'Ionomer_Type',
       'Anode_Metal_Loading_mg_cm2__Ir_Ru_Pt_Pd', 'Cathode_Loading_mg_cm2',
       'Electrolyte', 'Ligh_Intensity_mW_cm2_', 'CH4_Flow_rate_sscm',
       'Methanol_Yield_micromol_ml_', 'Ethanol_Yield_micromol_ml_',
       'Voltage_V', 'Current_at_1.5_V', 'Current_at_1.6_V', 'Current_at_1.7_V',
       'Current_at_1.8_V', 'Current_at_1.9_V', 'Current_at_2.0_V',
       'Operating_Pressure_bar', 'Current_Density_mA_cm2', 'Reaction_Time_hr',
       'Process_type'],
      dtype='object')

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
    ETL Pipeline- Transform
</center></p></h1>

In [33]:
df = df.fillna(0)  # replace all NaN with 0

In [ ]:

df = df.dropna()

if 'timestamp' in df.columns:
    df['timestamp'] = pd.to_datetime(df['timestamp'])

if 'energy_kwh' in df.columns:
    df = df[df['energy_kwh'] > 0]

if 'energy_kwh' in df.columns:
    df['energy_mwh'] = df['energy_kwh'] / 1000

print(f"Cleaned data shape: {df.shape}")

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
    DataBase -Saving
</center></p></h1>

In [34]:


# ---- Send data to MySQL ----
df.to_sql(
    table_name,
    con=engine,
    if_exists='replace',  # 'append' 
    index=False
)

print("Data successfully loaded back into the database!")

Data successfully loaded back into the database!

<h1><p><center style="background: linear-gradient(to right,white,green);color: transparent;font-family: Gabriola;color: navy;font-size: 80%;text-align: center;border-radius: 10px 70px">
   Query
</center></p></h1>

In [37]:
df_cols = pd.read_sql("SHOW COLUMNS FROM preprocessed", engine)
print(df_cols)

                                      Field    Type Null Key Default Extra
0                           Cathod_Catalyst    text  YES        None
1                            Anode_Catalyst    text  YES        None
2             Pt_atpercent_in_metal_element  bigint  YES        None
3             Co_atpercent_in_metal_element  bigint  YES        None
4             Ni_atpercent_in_metal_element  bigint  YES        None
5             Pd_atpercent_in_metal_element  bigint  YES        None
6             Ir_atpercent_in_metal_element  bigint  YES        None
7             Zr_atpercent_in_metal_element  double  YES        None
8             Ru_atpercent_in_metal_element  double  YES        None
9               Grahene_percent__as_support  double  YES        None
10                       Biocatalystpercent  double  YES        None
11                  TiO2_percent_as_support  bigint  YES        None
12                  CeO2_percent_as_support  double  YES        None
13               g_C3N4_percent__as_support  bigint  YES        None
14                      Cpercent_as_support  bigint  YES        None
15              Total_Metal_Loading_percent  double  YES        None
16                     BET_surface_aream2_g  double  YES        None
17                           Ink__I_C_Ratio    text  YES        None
18                           Membrance_Type    text  YES        None
19                          Active_Area_cm2  bigint  YES        None
20                             Ionomer_Type    text  YES        None
21  Anode_Metal_Loading_mg_cm2__Ir_Ru_Pt_Pd  double  YES        None
22                   Cathode_Loading_mg_cm2  double  YES        None
23                              Electrolyte    text  YES        None
24                   Ligh_Intensity_mW_cm2_  bigint  YES        None
25                       CH4_Flow_rate_sscm  bigint  YES        None
26              Methanol_Yield_micromol_ml_  double  YES        None
27               Ethanol_Yield_micromol_ml_  double  YES        None
28                                Voltage_V  double  YES        None
29                         Current_at_1.5_V  double  YES        None
30                         Current_at_1.6_V  double  YES        None
31                         Current_at_1.7_V  double  YES        None
32                         Current_at_1.8_V  double  YES        None
33                         Current_at_1.9_V  double  YES        None
34                         Current_at_2.0_V  double  YES        None
35                   Operating_Pressure_bar  double  YES        None
36                   Current_Density_mA_cm2  double  YES        None
37                         Reaction_Time_hr  bigint  YES        None
38                             Process_type    text  YES        None

In [39]:
sql= """ SELECT *
FROM preprocessed
WHERE  Methanol_Yield_micromol_ml_ IS NOT NULL"""

df = pd.read_sql(sql, engine)
df.head()

,Cathod_Catalyst,Anode_Catalyst,Pt_atpercent_in_metal_element,Co_atpercent_in_metal_element,Ni_atpercent_in_metal_element,Pd_atpercent_in_metal_element,Ir_atpercent_in_metal_element,Zr_atpercent_in_metal_element,Ru_atpercent_in_metal_element,Grahene_percent__as_support,...,Current_at_1.5_V,Current_at_1.6_V,Current_at_1.7_V,Current_at_1.8_V,Current_at_1.9_V,Current_at_2.0_V,Operating_Pressure_bar,Current_Density_mA_cm2,Reaction_Time_hr,Process_type
0,Ni-Tio2,IrO₂,-1,1,89,0,0,0.388158,0.465456,0.287554,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.004461,31.555958,2,Electrolyzer
1,Pd-Ni/CeO2,IrO₂,1,1,1,0,0,-0.110492,0.213468,-0.126233,...,0.121830,0.420827,0.847900,1.238966,1.618621,2.018211,1.005696,86.842445,6,Electrolyzer
2,Pt-Co/TiO2/g-C3N4,NiFeO2,48,51,0,0,1,0.335529,-0.455251,-0.057967,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.999690,80.215411,9,Solar light
3,Ru/TiO2/g-C3N4,IrO₂,-1,0,1,0,0,-0.441902,99.305976,-0.791599,...,0.253608,0.793055,1.374248,2.051113,2.637428,3.175515,0.994959,63.177526,6,Electrochemical devices
4,Pt/TiO2,IrO₂,100,1,1,0,-1,-0.205660,0.044834,-0.114413,...,0.222016,0.537653,0.859000,1.113203,1.474970,2.021662,1.561931,54.845526,6,Electrolyzer

# Average Yield per Catalyst Combination

In [43]:
sql= """ SELECT 
    cathod_catalyst,
    anode_catalyst,
    AVG(Methanol_Yield_micromol_ml_) AS avg_yield,
    COUNT(*) AS experiment_count
FROM preprocessed
GROUP BY cathod_catalyst, anode_catalyst
ORDER BY avg_yield DESC """

df = pd.read_sql(sql, engine)
df.head()

   cathod_catalyst        anode_catalyst  avg_yield  experiment_count
0      Tio2/g-C3N4                NiFeO2  13.557872                 1
1       Pd-Ni/CeO2  iridium_oxide_(iro2)  13.481925                 1
2       Pd-Ni/CeO2                  IrO₂  11.963274                39
3  Pt-Ni/TiO2/CeO2                  IrO₂  11.356387                11
4          Ru/TiO2  iridium_oxide_(iro2)   8.026778                 1

# Yield Efficiency (Yield per Reaction Time)

In [47]:
sql= """ SELECT 
    cathod_catalyst,
    Methanol_Yield_micromol_ml_ / Reaction_Time_hr AS efficiency FROM preprocessed """

df=pd.read_sql(sql, engine)
df.head()

     cathod_catalyst  efficiency
0            Ni-Tio2    0.042518
1         Pd-Ni/CeO2    2.334242
2  Pt-Co/TiO2/g-C3N4    0.857736
3     Ru/TiO2/g-C3N4    0.220453
4            Pt/TiO2    0.303134

# Detect Duplicate Experimental Conditions

In [53]:
sql=""" SELECT 
    cathod_catalyst,
    anode_catalyst,
     Voltage_V,
    CH4_Flow_rate_sscm,
    COUNT(*) AS duplicates
FROM preprocessed
GROUP BY 
    cathod_catalyst,
    anode_catalyst,
     Voltage_V,
    CH4_Flow_rate_sscm
HAVING COUNT(*) > 1"""

df = pd.read_sql(sql, engine)
df.head()

Empty DataFrame
Columns: [cathod_catalyst, anode_catalyst, Voltage_V, CH4_Flow_rate_sscm, duplicates]
Index: []

# Catalyst Metal Composition Summary

In [50]:
sql=""" SELECT
    process_type,
    AVG(Pt_atpercent_in_metal_element) AS avg_pt,
    AVG(Ni_atpercent_in_metal_element) AS avg_ni,
    AVG(Co_atpercent_in_metal_element) AS avg_pd
FROM preprocessed
GROUP BY process_type"""

df = pd.read_sql(sql, engine)
df.head()

              process_type   avg_pt   avg_ni   avg_pd
0             Electrolyzer  44.0315   8.1514  15.4101
1              Solar light  47.1045  12.8955  26.7836
2  Electrochemical devices  26.0000   4.8298   2.7234